name: buaberry_web
description: buaberry web official
publish_to: 'none'

version: 0.0.5+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  path_provider: ^2.1.5
  flutter_displaymode: ^0.6.0
  easy_localization: ^3.0.7
  ionicons: ^0.2.2
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.6.1
  dio: ^5.8.0+1
  freezed_annotation: ^3.0.0
  logger: ^2.5.0
  get_storage: ^2.1.1
  gap: ^3.0.1
  network_logger: ^1.0.4
  json_annotation: ^4.9.0
  go_router: ^16.2.4
  fpdart: ^1.1.0
  responsive_builder: ^0.7.0
  flex_color_scheme: ^8.0.2
  url_launcher: ^6.1.11
  intl: ^0.20.2
  stack_trace: ^1.11.0
  google_fonts: ^6.2.1
  android_id: ^0.4.0
  hive_ce: ^2.11.1
  device_info_plus: ^11.4.0
  crypto: ^3.0.6
  hive_ce_flutter: ^2.3.0
  sizer: 3.1.3
  fluttertoast: 8.0.9
  flutter_svg: 1.1.1+1
  flutter_dotenv: 5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  riverpod_generator: ^2.6.4
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.4
  freezed: ^3.0.6
  rider: ^0.0.1
  hive_ce_generator: ^1.9.1
  riverpod_test: ^0.1.9

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/translations/
    - assets/img/
    - assets/images/
    - assets/images/menu/
    - assets/images/owner/
    - assets/images/shop/
    - assets/images/social/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300

